### ISSUE TITLE
No Windows binaries in the release

### ISSUE THREAD

**Issue by garethr** [cppforlife/knctl#37]
The GitHub releases page lists binaries for Linux and Darwin but not Windows. Are there any known issues with Windows support preventing this?

**Comment by drnic** [comment]
Cut Windows CLIs and wait for issues ;)

**Comment by cppforlife** [comment]
that i can definitely do next week.

**Comment by cppforlife** [comment]
> The build instructions don't include mention of dep, so if you just run the scripts or follow the README instructions it will fail due to missing dependencies

shouldnt be necessary to build. all dependencies are vendored in `vendor/`

```
 $ cd ~/workspace/

 $ git clone https://github.com/cppforlife/knctl knctl-go/src/github.com/cppforlife/knctl
Cloning into 'knctl-go/src/github.com/cppforlife/knctl'...
remote: Enumerating objects: 1812, done.
remote: Counting objects: 100% (1812/1812), done.
remote: Compressing objects: 100% (1143/1143), done.
remote: Total 6045 (delta 724), reused 1304 (delta 493), pack-reused 4233
Receiving objects: 100% (6045/6045), 7.08 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (3105/3105), done.
Checking connectivity... done.

 $ cd knctl-go/src/github.com/cppforlife/knctl

 $ export GOPATH=~/workspace/knctl-go/

 $ ./hack/build.sh
+ go fmt ./cmd/... ./pkg/... ./test/...
+ go build ./cmd/...
+ ./knctl version
Client Version: 0.0.10
...
```

**Comment by garethr** [comment]
I had a few output formatting issues when running on Windows, noting here:

```console
$ knctl basic-auth-secret create ...
?[1mName?[0m  docker-hub
?[1mType?[0m  kubernetes.io/basic-auth
```

```console
$ knctl service-account create ...
?[1mName?[0m  docker-hub-service-account
```

**Comment by cppforlife** [comment]
@garethr latest release (https://github.com/cppforlife/knctl/releases/tag/v0.1.0) includes windows binary now.

**Comment by cppforlife** [comment]
closing this issue, created separate issue for windows colors.
