### ISSUE TITLE
Rename to `kntl`?

### ISSUE THREAD

**Issue by tanzeeb** [cppforlife/knctl#43]
Since `knative` is pronounced Kay-native, the pronunciation of `knctl` is a bit confusing (Kun-control? Kay An Control?).

If we rename it to `kntl`, the pronounciation is straight forward. 

Happy to send a PR if there's agreement.

**Comment by n3wscott** [comment]
I have no idea how to say `kntl`. Kay'N tall?

Kay'N cuddle is pretty easy.

**Comment by cppforlife** [comment]
i agree with @n3wscott on this one.

**Comment by tanzeeb** [comment]
> If we rename it to kntl, the pronounciation is straight forward.

Maybe it wasn't so straight forward ;-)

> I have no idea how to say kntl. Kay'N tall?

It would be pronounced "control".

How about `kntrl`?

**Comment by cppforlife** [comment]
@tanzeeb will keep it as knctl.
