### ISSUE TITLE
knctl snap packaging

### ISSUE THREAD

**Issue by ipolyzos** [cppforlife/knctl#52]
I would like to share some work on packaging _**knctl**_ as a snap and kindly ask your feedback and thoughts. You can find the source on _https://github.com/ipolyzos/knctl-snap_ while the snaps can be downloaded directly from [snapcraft store](https://snapcraft.io/store) _(currently versions v0.0.10 and v0.1.0 are unploaded)_.

**Comment by cppforlife** [comment]
@ipolyzos looks good, though im curious why kubectl is in that snap.

**Comment by ipolyzos** [comment]
@cppforlife since _kucetl_ is a dependency I have kept it as part of the same package in order to keep this single and self-contained and provide a supported version of _kubectl_ by default.

**Comment by cppforlife** [comment]
@ipolyzos fair enough, do not know if snaps can depend on other snaps to pull dependencies.

**Comment by ipolyzos** [comment]
@cppforlife Snaps are expected to contain their dependencies both applications, and the necessary libraries needed for the applications to function correctly. The idea is for the developer to be always assured that there are no regressions triggered by changes to the system underneath their app ...

**Comment by ipolyzos** [comment]
@cppforlife as per the official docs, snaps, aim to bundle all of their dependencies and runtime, toward a self-containing package. A layered model of system and frameworks along deduplication mechanism are provided though.

**Comment by cppforlife** [comment]
i see. fair enough. thanks for sharing! this issue will should be findable in this repo and might be useful for some people.
