### ISSUE TITLE
Support for setting alternate Dockerfile

### ISSUE THREAD

**Issue by edwarnicke** [cppforlife/knctl#53]
I've got a project with more than a single Dockerfile, and where the Dockerfile is not in the root dir for the project.  I normally handle this with things like:

```bash
docker build -f docker/Dockerfile.foo .
```

I notice you guys have [hard coded the Dockerfile](https://github.com/cppforlife/knctl/blob/master/pkg/knctl/build/build_spec.go#L145).  Would you be open to a PR that makes that configurable through a command line flag?

**Comment by cppforlife** [comment]
@edwarnicke PR would be great.

**Comment by cppforlife** [comment]
closing, feel free to send a PR.
