### ISSUE TITLE
knctl vs "Sample API Usage" documentation

### ISSUE THREAD

**Issue by cdrage** [cppforlife/knctl#54]
Hey @cppforlife !

Quick question, I found this doc with a lot of CLI examples, from my Google-fu, these are simple "usage examples" and obviously don't reflect on something that's already created.

With regards to the examples here: https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md#3-managed-release-of-a-new-revision---config-change-only 

I'm assuming that'll reflect the development of `knctl`? I'd like to start contributing and I'm just curious if the above documentation is reflective of the "ROADMAP" of `knctl` and what it should look like.

**Comment by cdrage** [comment]
Would you say that this is the "ROADMAP" for `knctl`?

**Comment by cppforlife** [comment]
> I'm just curious if the above documentation is reflective of the "ROADMAP" of knctl and what it should look like.

it's not. knctl was created before knative/client project started. it represents views that i hold for what knative cli should be. some of those views align with above doc but plenty do not. knctl will continue to be a project that explores some of the different choices from knative/client. good ideas hopefully will be ported over.

**Comment by cppforlife** [comment]
closing this issue. if you have particular ideas and want to contribute, dont hesitate to start an issue/or slack discussion in knative slack.
