### ISSUE TITLE
knctl deploy --env parameter can't contain comma-separated value

### ISSUE THREAD

**Issue by jochenehret** [cppforlife/knctl#58]
We are trying to deploy a Java application like this:
```
knctl deploy ... --env JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
```
It seems that the env value is truncated after the first comma:
```
ERROR: JDWP invalid option: -agentlib:jdwp=transport=dt_socket
```
We've tried different quoting variations (single quotes around value, double quotes etc.), but without success. Can you please check?

Thanks a lot for your support!

**Comment by matthew1534** [comment]
I believe we have a similar/same issue - the error message isn't helpful in our case 
`Error: Expected environment variable to be in format 'ENV_KEY=value'`

Deployment:
`knctl deploy ... --env MONGO_DB_URI="mongodb://<USERNAME>:<PASSWORD>@shard-00-00-qpzhp.gcp.mongodb.net:27017,shard-00-01-qpzhp.gcp.mongodb.net:27017,shard-00-02-qpzhp.gcp.mongodb.net:27017/test?ssl=true&replicaSet=shard-0&authSource=admin&retryWrites=true"`

If we remove the env `MONGO_DB_URI` we don't get this error message

knctl is great; really appreciate all the work that's gone into it!

**Comment by cppforlife** [comment]
@jochenehret @matthew1534 fix is in this commit: https://github.com/cppforlife/knctl/commit/1a23540a97ad719e633aa0a00b9535f360e21660. it's going through CI now; once it goes green i'll cut a new release.

thanks for reporting!

**Comment by cppforlife** [comment]
fixed in https://github.com/cppforlife/knctl/releases/tag/v0.2.0

> knctl is great; really appreciate all the work that's gone into it!

glad you find it useful!
