### ISSUE TITLE
Add support for knative pipeline spin-off https://github.com/tektoncd/pipeline 

### ISSUE THREAD

**Issue by number5** [cppforlife/knctl#62]
https://github.com/tektoncd/pipeline is almost the same as knative/pipeline, can be installed alone without Istio, would be great if `knctl` can support it

**Comment by cppforlife** [comment]
> would be great if knctl can support it

@number5 do you mean have an install option for it? or something else?

if you are talking about just installing it, i would recommend using https://github.com/k14s/kapp (just open sourced)

**Comment by number5** [comment]
I mean to use knctl to create build jobs on tekton pipeline (assuming they are using almost identical manifests)

**Comment by cppforlife** [comment]
@number5 i would say at this point, now that tekton is a dedicated project (not really part of knative), it doesnt make sense to include it in knctl. we'll see what happens with current knative build and its integration with knative serving.

**Comment by number5** [comment]
yep, that make sense.
